#!/bin/sh
# Выполняется один раз при создании тома БД.
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<SQL
CREATE ROLE pact_app LOGIN PASSWORD '$APP_DB_PASSWORD';
GRANT CONNECT ON DATABASE $POSTGRES_DB TO pact_app;
GRANT USAGE ON SCHEMA public TO pact_app;
ALTER DEFAULT PRIVILEGES FOR ROLE $POSTGRES_USER IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO pact_app;
ALTER DEFAULT PRIVILEGES FOR ROLE $POSTGRES_USER IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO pact_app;
SQL
